"""
DOCX renderer (Pass 3).

Converts authored markdown content into a board-packet-quality Word
document using python-docx. The renderer's external contract is the
same as the other renderers in this package:

    render(content, title, include_audit_footer, audit_metadata) -> bytes

Bytes are returned (not a file path) so the storage backend remains
responsible for persistence. This separation lets cloud backends
(Google Drive, OneDrive, SharePoint in v2) upload the same bytes
without changes here.

Design choices (locked in Pass 3 design discussion):
  - Cover page when title is provided (title, optional status/audience
    from audit_metadata, generated date, "Generated by ADAM", page break)
  - Mirror the HTML renderer's markdown coverage: H1-H6, paragraphs with
    inline bold/italic/code, bulleted/numbered lists, pipe tables,
    fenced code blocks, horizontal rules, links
  - End-of-document audit footer (NOT a repeating page footer, per v1
    decision -- page-footer mode can be added later as an opt-in arg)
  - Page numbers in the standard footer (separate from audit metadata)
  - Document properties always populated: title, author, subject,
    comments, keywords -- so the file is self-describing when detached
    from ADAM's logs
  - Calibri 11pt body, 1-inch margins, headings styled for visual hierarchy
  - Tables have a shaded header row
  - Code blocks render as monospace paragraphs with a light gray background
  - Links render as blue underlined text and a real Word hyperlink when
    the URL is well-formed

Governance preserved:
  - Renderer produces bytes only -- no file paths, no network, no
    arbitrary I/O
  - The handler enforces filename sanitization and content size limits
    before this code runs
"""

import io
import re
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

# python-docx imports. We import at module load (not lazily inside
# render()) so a missing dependency surfaces clearly during skill
# discovery rather than at first invocation. requirements.txt already
# pins python-docx; if it's missing the dependency check at startup
# warns about it.
from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Cm, Inches, Pt, RGBColor


# ============================================================
# Styling constants
# ============================================================

# Body font + size. Calibri 11 is the cross-platform-safe choice for
# board-facing documents. Aptos (Word's newer default) is fine if it
# resolves, but falls back to Calibri otherwise.
BODY_FONT_NAME    = "Calibri"
BODY_FONT_SIZE_PT = 11

# Code-block font: monospace, slightly smaller so blocks don't dominate
# visually. Consolas is Word's standard monospace; falls back to
# Courier New on systems without it.
CODE_FONT_NAME    = "Consolas"
CODE_FONT_SIZE_PT = 10

# Colors. RGBColor takes ints, not hex strings.
COLOR_HEADING_2_BORDER = RGBColor(0xBF, 0xBF, 0xBF)  # subtle grey
COLOR_TABLE_HEADER_BG  = "EEEEEE"                    # used as hex in XML
COLOR_CODE_BG          = "F5F5F5"                    # used as hex in XML
COLOR_LINK             = RGBColor(0x05, 0x63, 0xC1)  # Word's hyperlink blue
COLOR_AUDIT_FOOTER     = RGBColor(0x80, 0x80, 0x80)  # mid-grey
COLOR_COVER_SUBTLE     = RGBColor(0x80, 0x80, 0x80)


# ============================================================
# Helpers for low-level XML manipulation
# ============================================================
#
# python-docx exposes most of what we need through its high-level API,
# but a few details (table cell shading, paragraph borders, real
# hyperlinks, page numbers) require dropping to the underlying OOXML.
# We isolate the XML-fiddling in these helpers so the main render
# functions stay readable.

def _set_cell_shading(cell, fill_hex: str) -> None:
    """Apply background shading to a table cell."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill_hex)
    tc_pr.append(shd)


def _set_paragraph_shading(paragraph, fill_hex: str) -> None:
    """Apply background shading to a paragraph (used for code blocks)."""
    p_pr = paragraph._p.get_or_add_pPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill_hex)
    p_pr.append(shd)


def _set_paragraph_bottom_border(paragraph, color_hex: str = "BFBFBF",
                                  size: str = "6") -> None:
    """Add a bottom border to a paragraph (used for hr and H2 styling)."""
    p_pr = paragraph._p.get_or_add_pPr()
    p_bdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), size)
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), color_hex)
    p_bdr.append(bottom)
    p_pr.append(p_bdr)


def _add_page_field(paragraph) -> None:
    """
    Insert a PAGE field into a paragraph. Used to put page numbers in
    the footer. This is the OOXML pattern for "dynamic field that Word
    evaluates at render time."
    """
    run = paragraph.add_run()
    fld_char_begin = OxmlElement("w:fldChar")
    fld_char_begin.set(qn("w:fldCharType"), "begin")
    instr_text = OxmlElement("w:instrText")
    instr_text.set(qn("xml:space"), "preserve")
    instr_text.text = "PAGE"
    fld_char_end = OxmlElement("w:fldChar")
    fld_char_end.set(qn("w:fldCharType"), "end")
    run._r.append(fld_char_begin)
    run._r.append(instr_text)
    run._r.append(fld_char_end)


def _add_hyperlink(paragraph, text: str, url: str) -> None:
    """
    Add a real Word hyperlink (clickable in Word and downstream systems).
    Renders as blue underlined text. If the URL is malformed and
    relationship creation fails, we degrade gracefully to a styled run
    so the visible text is preserved.
    """
    try:
        part = paragraph.part
        r_id = part.relate_to(
            url,
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
            is_external=True,
        )
    except Exception:
        # Malformed URL or relationship failure: just render as styled text
        run = paragraph.add_run(text)
        run.font.color.rgb = COLOR_LINK
        run.font.underline = True
        return

    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)

    new_run = OxmlElement("w:r")
    r_pr = OxmlElement("w:rPr")
    # Blue color
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "0563C1")
    r_pr.append(color)
    # Underline
    underline = OxmlElement("w:u")
    underline.set(qn("w:val"), "single")
    r_pr.append(underline)
    new_run.append(r_pr)
    text_el = OxmlElement("w:t")
    text_el.set(qn("xml:space"), "preserve")
    text_el.text = text
    new_run.append(text_el)
    hyperlink.append(new_run)

    paragraph._p.append(hyperlink)


# ============================================================
# Inline markdown -> Word runs
# ============================================================
#
# We hand-roll inline parsing rather than depend on a markdown library
# so the renderer stays stdlib + python-docx only. The supported
# patterns mirror the HTML renderer:
#   `code`               -> monospace run
#   **bold**             -> bold run
#   __bold__             -> bold run
#   *italic*             -> italic run (no mid-word matches)
#   _italic_             -> italic run (no mid-word matches)
#   [text](url)          -> real hyperlink
# Anything not matching is added as plain text.

# Inline tokenizer: ordered list of (pattern, kind) tuples. Order
# matters -- code spans first so their contents aren't interpreted as
# bold/italic; then links; then bold; then italic.
_INLINE_PATTERNS: List[Tuple[re.Pattern, str]] = [
    (re.compile(r"`([^`]+)`"),                                 "code"),
    (re.compile(r"\[([^\]]+)\]\(([^)]+)\)"),                   "link"),
    (re.compile(r"\*\*([^*]+)\*\*"),                            "bold"),
    (re.compile(r"__([^_]+)__"),                                "bold"),
    (re.compile(r"(?<!\w)\*([^*\n]+)\*(?!\w)"),                 "italic"),
    (re.compile(r"(?<!\w)_([^_\n]+)_(?!\w)"),                   "italic"),
]


def _tokenize_inline(text: str) -> List[Tuple[str, Any]]:
    """
    Tokenize a line into ('text', str), ('code', str), ('bold', str),
    ('italic', str), or ('link', (text, url)) tuples.

    Strategy: scan the text once, repeatedly finding the earliest match
    across all patterns. Whatever sits before the earliest match is a
    plain-text token; the match itself becomes a styled token; then we
    continue from the end of the match.
    """
    tokens: List[Tuple[str, Any]] = []
    pos = 0
    while pos < len(text):
        earliest: Optional[Tuple[int, re.Match, str]] = None
        for pattern, kind in _INLINE_PATTERNS:
            m = pattern.search(text, pos)
            if m and (earliest is None or m.start() < earliest[0]):
                earliest = (m.start(), m, kind)
        if earliest is None:
            tokens.append(("text", text[pos:]))
            break
        start, match, kind = earliest
        if start > pos:
            tokens.append(("text", text[pos:start]))
        if kind == "link":
            tokens.append(("link", (match.group(1), match.group(2))))
        else:
            tokens.append((kind, match.group(1)))
        pos = match.end()
    return tokens


def _add_inline_to_paragraph(paragraph, text: str) -> None:
    """Render inline markdown into runs on the given paragraph."""
    for kind, value in _tokenize_inline(text):
        if kind == "link":
            link_text, url = value
            _add_hyperlink(paragraph, link_text, url)
            continue
        run = paragraph.add_run(value)
        if kind == "code":
            run.font.name = CODE_FONT_NAME
            run.font.size = Pt(CODE_FONT_SIZE_PT)
        elif kind == "bold":
            run.bold = True
        elif kind == "italic":
            run.italic = True
        # 'text' is plain; no styling needed


# ============================================================
# Document-level helpers
# ============================================================

def _set_base_styles(doc: Document) -> None:
    """Set the Normal style font + size for the whole document."""
    normal = doc.styles["Normal"]
    normal.font.name = BODY_FONT_NAME
    normal.font.size = Pt(BODY_FONT_SIZE_PT)
    # 1-inch margins on all sides
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1)
        section.right_margin  = Inches(1)


def _add_page_number_footer(doc: Document) -> None:
    """Place 'Page X' in the default section footer."""
    for section in doc.sections:
        footer = section.footer
        # If the footer already has a paragraph (it always does in
        # python-docx-created docs), use it; otherwise create one.
        para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.text = ""  # clear any default
        run = para.add_run("Page ")
        run.font.size = Pt(9)
        _add_page_field(para)


def _populate_core_properties(
    doc:        Document,
    title:      Optional[str],
    audit_meta: Optional[Dict[str, Any]],
) -> None:
    """
    Always-populate document properties so the file is self-describing
    when opened outside ADAM's log directory.
    """
    cp = doc.core_properties
    cp.title    = title or "Untitled ADAM artifact"
    cp.author   = "ADAM (Adaptive Dynamic Agent Multiplex)"
    cp.keywords = "ADAM, deliberation, audit-grade"
    if audit_meta:
        session_id    = str(audit_meta.get("session_id", "")) or "unknown"
        invocation_id = str(audit_meta.get("invocation_id", "")) or "unknown"
        artifact_id   = str(audit_meta.get("artifact_id", "")) or "unknown"
        generated     = str(audit_meta.get("generated", "")) or "unknown"
        fmt           = str(audit_meta.get("format", "docx"))
        cp.subject = f"ADAM-generated artifact ({fmt}) - session {session_id}"
        cp.comments = (
            f"invocation_id={invocation_id} | "
            f"artifact_id={artifact_id} | "
            f"generated={generated}"
        )
    else:
        cp.subject  = "ADAM-generated artifact"
        cp.comments = ""
    # python-docx's CoreProperties doesn't expose 'category' as a
    # setter on all versions, so we set it via the underlying element
    # when accessible. Failing silently is fine -- category is nice-
    # to-have, not load-bearing for board readability.
    try:
        cp.category = "ADAM Artifact"
    except AttributeError:
        pass


def _add_cover_page(
    doc:        Document,
    title:      str,
    audit_meta: Optional[Dict[str, Any]],
) -> None:
    """
    Add a cover page. Called only when title is provided.
    Layout (top-to-bottom):
      - vertical space
      - Title (large, centered)
      - Optional status line from audit_meta.status
      - Optional audience line from audit_meta.audience (if set)
      - vertical space
      - Generated date
      - "Generated by ADAM"
      - hard page break
    """
    # Top spacing: a few empty paragraphs push the title down to roughly
    # the upper third of the page. Could be done with section spacing,
    # but blank paragraphs are simpler and work consistently.
    for _ in range(6):
        doc.add_paragraph()

    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(title)
    title_run.bold = True
    title_run.font.size = Pt(28)
    title_run.font.name = BODY_FONT_NAME

    # Status subtitle (e.g. "Status: Draft") if present
    status = (audit_meta or {}).get("status")
    if status:
        sub_para = doc.add_paragraph()
        sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_run = sub_para.add_run(f"Status: {status}")
        sub_run.italic = True
        sub_run.font.size = Pt(14)
        sub_run.font.color.rgb = COLOR_COVER_SUBTLE

    # Audience line if present
    audience = (audit_meta or {}).get("audience")
    if audience:
        aud_para = doc.add_paragraph()
        aud_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        aud_run = aud_para.add_run(f"Prepared for: {audience}")
        aud_run.italic = True
        aud_run.font.size = Pt(12)
        aud_run.font.color.rgb = COLOR_COVER_SUBTLE

    # More vertical space before the bottom block
    for _ in range(8):
        doc.add_paragraph()

    # Generated date
    generated = (audit_meta or {}).get("generated", "")
    if generated:
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(f"Generated: {generated}")
        date_run.font.size = Pt(11)
        date_run.font.color.rgb = COLOR_COVER_SUBTLE

    # "Generated by ADAM"
    byline = doc.add_paragraph()
    byline.alignment = WD_ALIGN_PARAGRAPH.CENTER
    byline_run = byline.add_run("Generated by ADAM (Adaptive Dynamic Agent Multiplex)")
    byline_run.font.size = Pt(11)
    byline_run.font.color.rgb = COLOR_COVER_SUBTLE
    byline_run.italic = True

    # Hard page break to end the cover page
    break_para = doc.add_paragraph()
    break_para.add_run().add_break(WD_BREAK.PAGE)


def _add_heading(doc: Document, level: int, text: str) -> None:
    """
    Add a heading at the given level. python-docx's built-in 'Heading 1'
    through 'Heading 9' styles provide the right visual hierarchy.
    Level 2 gets a subtle bottom border for extra visual separation
    in board-facing documents.
    """
    level = max(1, min(level, 6))
    heading = doc.add_heading(level=level)
    _add_inline_to_paragraph(heading, text.strip())
    if level == 2:
        _set_paragraph_bottom_border(heading, color_hex="BFBFBF", size="4")


def _add_paragraph(doc: Document, text: str) -> None:
    """Add a normal paragraph with inline markdown rendered."""
    para = doc.add_paragraph()
    _add_inline_to_paragraph(para, text)


def _add_bullet(doc: Document, text: str, level: int = 0) -> None:
    """Add a bulleted-list item at the given nesting level."""
    # python-docx exposes 'List Bullet', 'List Bullet 2', 'List Bullet 3'
    # for nesting levels 1, 2, 3. Levels deeper than that fall back to
    # level 3 since deeper styles aren't reliably present in default templates.
    style = "List Bullet" if level <= 0 else f"List Bullet {min(level + 1, 3)}"
    try:
        para = doc.add_paragraph(style=style)
    except KeyError:
        para = doc.add_paragraph(style="List Bullet")
    _add_inline_to_paragraph(para, text)


def _add_numbered(doc: Document, text: str, level: int = 0) -> None:
    """Add a numbered-list item at the given nesting level."""
    style = "List Number" if level <= 0 else f"List Number {min(level + 1, 3)}"
    try:
        para = doc.add_paragraph(style=style)
    except KeyError:
        para = doc.add_paragraph(style="List Number")
    _add_inline_to_paragraph(para, text)


def _add_code_block(doc: Document, code: str) -> None:
    """Render a fenced code block as a monospace paragraph with light
    grey background. Newlines inside the block become line breaks."""
    para = doc.add_paragraph()
    _set_paragraph_shading(para, COLOR_CODE_BG)
    lines = code.split("\n")
    for i, line in enumerate(lines):
        run = para.add_run(line)
        run.font.name = CODE_FONT_NAME
        run.font.size = Pt(CODE_FONT_SIZE_PT)
        if i < len(lines) - 1:
            run.add_break()


def _add_hr(doc: Document) -> None:
    """Render a horizontal rule as an empty paragraph with a bottom border."""
    para = doc.add_paragraph()
    _set_paragraph_bottom_border(para, color_hex="BFBFBF", size="6")


def _add_table(doc: Document, header_cells: List[str],
                body_rows: List[List[str]]) -> None:
    """
    Render a markdown pipe-style table as a Word table with a shaded,
    bold header row.
    """
    if not header_cells:
        return
    # Make all rows the same width as the header (pad short rows, trim
    # over-long rows so the visual layout stays predictable).
    width = len(header_cells)
    normalized_body = []
    for row in body_rows:
        if len(row) < width:
            row = row + [""] * (width - len(row))
        elif len(row) > width:
            row = row[:width]
        normalized_body.append(row)

    table = doc.add_table(rows=1 + len(normalized_body), cols=width)
    table.style = "Light Grid Accent 1"  # built-in style with visible borders
    table.autofit = True

    # Header
    header_row = table.rows[0]
    for i, cell_text in enumerate(header_cells):
        cell = header_row.cells[i]
        _set_cell_shading(cell, COLOR_TABLE_HEADER_BG)
        # Clear default paragraph, add our own with bold inline content
        cell.text = ""
        para = cell.paragraphs[0]
        run = para.add_run("")
        # Render inline (handles **bold** if author put it in headers)
        _add_inline_to_paragraph(para, cell_text.strip())
        # Force header text to bold regardless of inline state
        for r in para.runs:
            r.bold = True
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

    # Body
    for row_idx, row in enumerate(normalized_body, start=1):
        for col_idx, cell_text in enumerate(row):
            cell = table.rows[row_idx].cells[col_idx]
            cell.text = ""
            para = cell.paragraphs[0]
            _add_inline_to_paragraph(para, cell_text.strip())


def _add_audit_footer(doc: Document, audit_meta: Dict[str, Any]) -> None:
    """
    Append an end-of-document audit metadata block. Per Pass 3 decision,
    this is NOT a repeating page footer -- it's a styled block at the
    very end of the document, after the main content.
    """
    # Visual separator: bordered empty paragraph
    sep = doc.add_paragraph()
    _set_paragraph_bottom_border(sep, color_hex="BFBFBF", size="6")

    # Header
    header_para = doc.add_paragraph()
    header_run = header_para.add_run("Audit metadata")
    header_run.bold = True
    header_run.font.color.rgb = COLOR_AUDIT_FOOTER
    header_run.font.size = Pt(10)

    # Per-key lines
    for key, value in audit_meta.items():
        line = doc.add_paragraph()
        run = line.add_run(f"{key}: {value}")
        run.font.color.rgb = COLOR_AUDIT_FOOTER
        run.font.size = Pt(9)
        run.italic = True


# ============================================================
# Block-level markdown parser
# ============================================================
#
# We re-walk the content line by line and dispatch to the appropriate
# add_* helper. This mirrors the HTML renderer's block dispatcher; the
# only differences are the output target (a Word document via python-
# docx) and the styling decisions baked into the helpers above.

def _parse_and_render_blocks(doc: Document, content: str) -> None:
    """Walk the markdown content and render each block into the doc."""
    lines = content.splitlines()
    i = 0
    para_buffer: List[str] = []

    def flush_paragraph() -> None:
        if para_buffer:
            joined = " ".join(line.strip() for line in para_buffer)
            _add_paragraph(doc, joined)
            para_buffer.clear()

    while i < len(lines):
        line = lines[i]

        # Code fence: ``` to ```
        if line.strip().startswith("```"):
            flush_paragraph()
            code_lines: List[str] = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            _add_code_block(doc, "\n".join(code_lines))
            i += 1
            continue

        # Header
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            flush_paragraph()
            level = len(m.group(1))
            _add_heading(doc, level, m.group(2).strip())
            i += 1
            continue

        # Horizontal rule
        if re.match(r"^[-*_]{3,}\s*$", line):
            flush_paragraph()
            _add_hr(doc)
            i += 1
            continue

        # Unordered list (with simple nesting based on leading spaces)
        if re.match(r"^\s*[-*+]\s+", line):
            flush_paragraph()
            while i < len(lines) and re.match(r"^\s*[-*+]\s+", lines[i]):
                lead = len(lines[i]) - len(lines[i].lstrip())
                level = lead // 2  # 2 spaces per nesting level (CommonMark-ish)
                item_text = re.sub(r"^\s*[-*+]\s+", "", lines[i])
                _add_bullet(doc, item_text, level=level)
                i += 1
            continue

        # Ordered list
        if re.match(r"^\s*\d+\.\s+", line):
            flush_paragraph()
            while i < len(lines) and re.match(r"^\s*\d+\.\s+", lines[i]):
                lead = len(lines[i]) - len(lines[i].lstrip())
                level = lead // 3  # numbered lists indent more naturally
                item_text = re.sub(r"^\s*\d+\.\s+", "", lines[i])
                _add_numbered(doc, item_text, level=level)
                i += 1
            continue

        # Table: pipe-style with header separator on next line
        if ("|" in line and i + 1 < len(lines)
                and re.match(r"^\s*\|?[-:\s|]+\|?\s*$", lines[i + 1])):
            flush_paragraph()
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2  # skip the separator
            body: List[List[str]] = []
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                row = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                body.append(row)
                i += 1
            _add_table(doc, header, body)
            continue

        # Blank line -> paragraph break
        if not line.strip():
            flush_paragraph()
            i += 1
            continue

        # Default: accumulate into a paragraph
        para_buffer.append(line.strip())
        i += 1

    flush_paragraph()


# ============================================================
# Public render() entrypoint
# ============================================================

def render(
    content:              str,
    title:                Optional[str]            = None,
    include_audit_footer: bool                     = True,
    audit_metadata:       Optional[Dict[str, Any]] = None,
) -> bytes:
    """
    Render markdown content as a board-packet-quality .docx.

    Args:
        content:              The authored markdown content.
        title:                Optional document title. When provided, a
                              cover page is generated.
        include_audit_footer: When True (default), an end-of-document
                              audit metadata block is appended.
        audit_metadata:       Dict of audit fields (session_id,
                              invocation_id, artifact_id, generated,
                              format, status, audience, etc.). Used
                              for both the cover page (status, audience)
                              and the end-of-document audit footer, and
                              copied into Word document properties.

    Returns:
        The .docx file content as bytes, ready for the storage backend
        to write.
    """
    doc = Document()

    _set_base_styles(doc)
    _populate_core_properties(doc, title=title, audit_meta=audit_metadata)
    _add_page_number_footer(doc)

    # Cover page (only if a title was provided -- per Pass 3 decision,
    # we don't fabricate a cover page when the caller didn't ask for one)
    if title:
        _add_cover_page(doc, title=title, audit_meta=audit_metadata)

    # Main content
    _parse_and_render_blocks(doc, content)

    # End-of-document audit block
    if include_audit_footer and audit_metadata:
        _add_audit_footer(doc, audit_metadata)

    # Serialize to bytes via in-memory buffer (no filesystem touch here;
    # the storage backend owns persistence)
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
